name: Run Tests

permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]


jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
                ref: ${{ github.event.pull_request.head.sha }}

            - name: Install Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install pre-commit
              run: pip install pre-commit

            - name: Run pre-commit checks
              run: pre-commit run --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }} --show-diff-on-failure --color=always

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install everything
              run: pip install -e .[tests]

            - name: Run Unit Tests
              run: pytest -vv
